name: Waka Readme

on:
  schedule:
    # Runs At 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme With Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: i8o8i-Developer/i8o8i-WakaTime-Stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "True"
          PUSH_BRANCH_NAME: "main"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_COMMIT: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_SHORT_INFO: "True"
          SYMBOL_VERSION: 1
          COMMIT_USERNAME: "Readme-Bot"
          COMMIT_EMAIL: "i8o8i[bot]@i8o8i.org"
          COMMIT_MESSAGE: "ðŸ•’ Updated With Dev Metrics"

